---
title: "Investigating Key Factors for Social Network Evolution and Opinion Dynamics in an Agent-Based Simulation"
title-running: "Social Network Evolution and Opinion Dynamics"
author-inputfile: "authors.tex" 
abstract: |
  In recent years social media platforms have experienced an increasing attention of researchers due to their capabilities of providing information and spreading opinions of individuals, thus establishing a new environment for opinion formation on a societal level. To gain a better understanding of the occuring opinion dynamics, the interactions between the users and the content that has been shared in those environments has to be investigated. With our work we want to shed light on the part played by the underlying network structure as information spread relies directly on it and every user of social media is affected by it. We therefore analyzed the role of network properties and dealing with friendships in such networks using an agent-based model. Our results reveal the capability of such models for investigating the influence of these factors on opinion dynamics and encourage for further investigation in this field of research.
keywords: "Opinion Dynamics \\and Social Networks Analysis \\and Agent-based Modelling \\and Network Evolution."
bibliography: ["rpackages.bib", "bibliography.bib"]
#biblio-style: "apalike"
link-citations: true
output:
  bookdown::pdf_document2:
    fig_caption: true
    keep_tex: true
    template: lncs-template.tex
    md_extensions: +footnotes
    citation_package: biblatex
    dev: pdf
    
---


```{r knitr_init, echo=FALSE, message=FALSE, warning=FALSE, cache=FALSE, paged.print=TRUE}
## Global options
library(knitr)
#options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               out.width='100%'
               )
opts_knit$set(width=100)

# Load required libraries
library(rmdformats)
library(rmdtemplates)
library(tidyverse)
library(cowplot)
# add libraries here

# Add libraries to cite here:
pkgs <- c("knitr", "tidyverse", "rmdformats", "scales", "psych", "rmdtemplates")
rmdtemplates::write_bib(pkgs)
```


<!-- You may include external Rmd-Files. Turn on off by switching Eval-->
```{r introduction, eval=TRUE, child='10_introduction.Rmd'}
```
```{r relwork, eval=TRUE, child='20_relwork.Rmd'}
```
```{r method, eval=TRUE, child='30_method.Rmd'}
```
```{r results, eval=TRUE, child='40_results.Rmd'}
```
```{r discussion, eval=TRUE, child='50_discussion.Rmd'}
```

# Acknowledgements {-}
This research was supported by the Digital Society research program funded by the Ministry of Culture and Science of the German State of North Rhine-Westphalia.
We would further like to thank the authors of the packages we have used.
```{r r_citations, eval=TRUE, include=TRUE, results="asis"}
rmdtemplates::line_cite(pkgs) # This creates a single line citing all packages
#rmdtemplates::list_cite(pkgs) # This creates a "thightlist" of all packages 
```

# References
