---
title: "analysis"
author: "Johannes Nakayama"
date: "3 12 2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggraph)
library(igraph)
library(stats)

library(plot3Drgl)
library(viridis)
library(dplyr)
library(gganimate)

```

```{r Data Import}

load("simulation/results.Rda")

simruns <- list.files(file.path("simulation", "dataexchange"))


for (i in 1:length(simruns)) {
  assign(paste0(simruns[i], "_agent_log"), read.csv(file.path("simulation", "dataexchange", simruns[i], "agent_log.csv")))
  # assign(paste0(simruns[i], "_post_log"), read.csv(file.path("simulation","dataexchange", simruns[i], "post_log.csv")))
  # assign(paste0(simruns[i], "_graph_final"),
  #           read_graph(file.path("simulation","dataexchange", simruns[i], paste0("graph_11.gml")), format = "gml"))
  assign(paste0(simruns[i], "_graph_undirected"), 
            read_graph(file.path("simulation","dataexchange", simruns[i], paste0("graph_undirected.gml")), format = "gml"))
  
  print(paste0("Run ", i, " complete"))
    
}

for (runname in simruns) {
  current_agent_log <- get(paste0(runname, "_agent_log"))
  current_graph <- get(paste0(runname, "_graph_final"))
  current_agent_log %>% 
    filter(TickNr == 1000) %>% 
    .$Opinion %>% 
    round(digits = 4) -> agent_opinions
  
  V(current_graph)$opinion <- agent_opinions
  write.graph(current_graph, paste0(runname,".gml"), format="gml")
}


for (runname in simruns) {
  plotit(runname)
}

```

```{r plotting}
plotit <- function(simrun) {
  nodecolorgrad <- colorRampPalette(c("green", "blue", "red"))(2001)
  current_agent_log <- get(paste0(simrun, "_agent_log"))
  current_graph <- get(paste0(simrun, "_graph_undirected"))
  
  V(current_graph)$label <- NA
  V(current_graph)$size <- 1 + degree(current_graph, mode="out") / length(V(current_graph)) * 30
  current_agent_log %>% 
      filter(TickNr == 1000) %>% 
      .$Opinion %>% 
      round(digits = 3) %>% 
      + 1 %>% 
      "*"(1000) + 1  -> agent_opinions
  
  nodecolors <- nodecolorgrad[agent_opinions]
  # clp <- cluster_label_prop(current_graph)
  cfg <- cluster_fast_greedy(current_graph)
  
  # plot(clp, current_graph, layout = layout_with_fr, col = nodecolors)
  # png(paste0(simrun, ".png"), 3000, 3000)
  # plot(clp, current_graph, layout = layout_with_fr, col = nodecolors)
  # dev.off()
  
  plot(cfg, current_graph, layout = layout_with_fr, col = nodecolors)
  png(paste0(simrun, ".png"), 3000, 3000)
  plot(cfg, current_graph, layout = layout_with_fr, col = nodecolors)
  dev.off()
}

```

```{r}
BAfinal_run10_agent_log %>% 
  filter(Indegree == 0) %>% 
  group_by(TickNr)

resultcomparison %>% 
  group_by(AddFriends) %>% 
  summarise(MeanOutdegree = mean(OutdegreeAVG), MeanOutdegreeSD = mean(OutdegreeSD), meanOpSD = mean(OpinionAVG), MeanCentrality = mean(CentralityAVG))

resultcomparison %>% 
  select(Agentcount, Edgecount, UnfriendThresh) %>% 
  mutate(RelEdgeCount = Edgecount/((Agentcount * Agentcount) - Agentcount) * 100) %>%
  filter(Agentcount == 1000) %>% 
  summarise(meanAgentcount = mean(RelEdgeCount))
  ggplot(data = ., aes(x=Agentcount, y=RelEdgeCount)) +
  # geom_line(aes(x=Agentcount, y=RelEdgeCount)) +
  geom_point(aes(color=UnfriendThresh)) +
  scale_color_viridis_c()

BAfinal_run10_agent_log %>% 
  max()


BAfinal_run03_agent_log %>% 
  filter(AgentID == 81)
  filter(AgentID == 389 | AgentID == 84)

BAfinal_run01_agent_log %>% 
  group_by(TickNr) %>% 
  summarize(Edgecount = mean(Outdegree)*max(AgentID))

resultcomparison %>% 
  ggplot(aes(y=OutdegreeAVG, x=Agentcount)) +
  geom_point()


  
  filter(TickNr == 1000) %>% 
  select(Component) %>% 
  max()
  round(digits = 1) %>% 
  +1 %>% 
  "*"(10)

nodecolorgrad <- colorRampPalette(c("green", "blue", "red"))
length(seq(-1,1, by=0.1))
nodecolors <- nodegolorgrad
nodecolorgrad(2001)


deg <- degree(BAv2_run01_graph_10, mode="out")
V(BAv2_run01_graph_10)$size <- deg
V(BAv2_run01_graph_10)$size <- 8
V(BAv2_run01_graph_10)$frame.color <- "white"
V(BAv2_run01_graph_10)$color <- "orange"
V(BAv2_run01_graph_10)$label <- "" 
E(BAv2_run01_graph_10)$arrow.size <- .2
plot(BAv2_run01_graph_10, layout=layout_with_drl)


```

```{r}

BAv2_run06_agent_log %>% 
  group_by(TickNr) %>% 
  summarise(MaxOutdegree = max(Outdegree)) %>%
  left_join(BAv2_run06_agent_log, .) %>% 
  filter(Outdegree == MaxOutdegree)
  mutate(MaxOutdegree = max(Outdegree))
  summarise(maxOutdegree = max(Outdegree))
  filter(Outdegree == max(Outdegree)) -> biggesthubs
  group_by(TickNr) %>% 
  summarise(meandeg = mean(Outdegree), maxcomp = max(Component))

histarraymatrix
ncol(histarraymatrix)

for (runname in simruns[26:28]){
  
  df <- get(paste0(runname, "_agent_log"))
  
  seq(0,100, by=1) %>%
    round(digits=1) %>%
    table() -> histarray


  for (i in 1:max(df$TickNr)){
    
    if (i %% ceiling(max(df$TickNr) / 10) == 0 ) cat(paste0(round(i / max(df$TickNr) * 100), '% --- '))
    df %>%
        filter(.$TickNr == i, .$ActiveState == "true") %>%
        .[,7] %>%
        round(digits=1) %>%
        table() %>%
        bind_rows(histarray,.) -> histarray
  }
  
  histarray[is.na(histarray)] <- 0
  histarray %>%
      .[-1,] %>%
      as.matrix() -> histarraymatrix
  
  assign(paste0(runname, "histarraymatrix_indegree"), histarraymatrix)
  
  # Build the 3D Histogram
  persp3Drgl(
      x=1:nrow(histarraymatrix), y = seq(0,100, by=1),
          contour=FALSE, z = histarraymatrix,
          box=FALSE, shade=0.1,
          xlab="", ylab="", zlab="",
          col=viridis(n=2000, direction = -1), colkey=FALSE, axes=FALSE
      )
  
  
  # Formatting the Output
  view3d(userMatrix=viewpoint, zoom=0.6)
  par3d(windowRect = c(405, 104, 1795, 984))
  aspect3d(x=1.4,y=1.2,z=0.5)
  bbox3d(color=c("#EEEEEE","#AAAAAA"), xlen = 0, ylen = 0, zlen = 0)
  grid3d(side="x++", col="white", lwd=2)
  grid3d(side="y++", col="white", lwd=2)
  grid3d(side="z--", col="white", lwd=2)
  axis3d('x--', at = seq(0,floor(max(df$TickNr)/200)*200, by=200))
  axis3d('y--')
  axis3d('z-+', at = seq(0,floor(max(histarraymatrix)/50)*50, by=50))
  mtext3d("Simulation Step", "x--", line=2)
  mtext3d("Opinion", "y--", line=2)
  mtext3d("Agent Count", "z-+", line=2)
  
  snapshot3d(paste0("output_", runname, ".png"))
  # rgl.close()
}
  

```


```{r}

# Prepare for 3D Histogram
viewpoint <- matrix(c(0.581680357,	-0.813347518,	-0.010670132,	27.88446792,
                      0.311022758,	0.210274488,	0.926849186,	41.81242048,
                      -0.751606762,	-0.54244858,	0.375282109,	-2.694485856,
                      0, 0, 0, 1), nrow = 4, byrow = TRUE)

# Build Array of Histograms

for (runname in simruns){
  
  df <- get(paste0(runname, "_agent_log"))
  
  seq(-1,1, by=0.1) %>%
    round(digits=1) %>%
    table() -> histarray
  
  if (exists(paste0(runname, "histarraymatrix"))) {
    histarraymatrix <- get(paste0(runname, "histarraymatrix"))
  } else {
    
    for (i in 1:max(df$TickNr)){
    
    if (i %% ceiling(max(df$TickNr) / 10) == 0 ) cat(paste0(round(i / max(df$TickNr) * 100), '% --- '))
    df %>%
        filter(.$TickNr == i) %>%
        .[,3] %>%
        round(digits=1) %>%
        table() %>%
        bind_rows(histarray,.) -> histarray
    }
    
    print("\n")
  
    histarray[is.na(histarray)] <- 0
    histarray %>%
        .[-1,] %>%
        as.matrix() -> histarraymatrix
    
    assign(paste0(runname, "histarraymatrix"), histarraymatrix)
    
  }
  
  # Build the 3D Histogram
  persp3Drgl(
      x=1:nrow(histarraymatrix), y = seq(-1,1, by=0.1),
          contour=FALSE, z = histarraymatrix,
          box=FALSE, shade=0.1, alpha=0.7,
          xlab="", ylab="", zlab="",
          col=viridis(n=2000, direction = -1), colkey=FALSE, axes=FALSE
      )
  
  
  # Formatting the Output
  view3d(userMatrix=viewpoint, zoom=0.6)
  par3d(windowRect = c(405, 104, 1795, 984))
  aspect3d(x=1.4,y=1.2,z=0.5)
  bbox3d(color=c("#EEEEEE","#AAAAAA"), xlen = 0, ylen = 0, zlen = 0)
  grid3d(side="x++", col="white", lwd=2)
  grid3d(side="y++", col="white", lwd=2)
  grid3d(side="z--", col="white", lwd=2)
  axis3d('x--', at = seq(0,floor(max(df$TickNr)/200)*200, by=200))
  axis3d('y--')
  axis3d('z-+', at = seq(0,floor(max(histarraymatrix)/50)*50, by=50))
  mtext3d("Simulation Step", "x--", line=2)
  mtext3d("Opinion", "y--", line=2)
  mtext3d("Agent Count", "z-+", line=2)
  
  snapshot3d(paste0("output_", runname, ".png"))
  rgl.close()
}


```


```{r}

# Build the 3D Histogram
  

data <- data.frame(MeanDegree = double(), Centrality = double(), Transitivity = double())
data
get(paste0(simruns[1], "_sim_df")) %>% 
  cbind(Run = simruns[1]) %>% 
  group_by(Run, TickNr) %>% 
  summarise(AVG_Indegree = sd(Indegree), AVG_Outdegree=sd(Outdegree)) %>% 
  ggplot(aes(x=TickNr)) +
  geom_line(aes(y=AVG_Indegree), color = "red") +
  geom_line(aes(y=AVG_Outdegree))
  bind_rows(data, .) -> data
  
  mean(closeness(cur_graph))
  membership(cur_graph)

  plot(cur_graph)
  cur_graph <- get(paste0("BA_run", str_pad(as.character(4), 2, pad = "0"), "_graph_", str_pad(as.character(10), 2, pad = "0")))
  
  rbind(data, data.frame(MeanDegree = mean(degree(cur_graph)), Centrality = mean(closeness(cur_graph)), Transitivity = transitivity(cur_graph)))
  
BA_run09_graph_02 %>% 
  transitivity()
  degree(mode="out") %>% 
  sd()
  
mean(degree(BA_run01_graph_10))  

rbind(data, c(simrun[1], i, ))

for (i in 1:1) {
  
  for (j in 0:10) {
    thisgraph <- get(paste0("BA_run", str_pad(as.character(i), 2, pad = "0"), "_graph_", str_pad(as.character(j), 2, pad = "0")))
    result <- c(max(degree(thisgraph, mode = "in")), max(degree(thisgraph, mode = "out")))
      
  }
}

data.frame()

bigbarabasidigraph_sim_df %>% 
  filter(TickNr == 200, ActiveState == "true") %>% 
  select(PerceivPublOpinion ,Opinion , Indegree) %>% 
  ggplot(aes(x=abs(Opinion - PerceivPublOpinion), y=Indegree)) +
  geom_point()

plot(bigbarabasidigraph_graph_10)

bigbarabasidigraph_graph_10 %>% 
  diameter() %>% 
  mean()
  
```

