---
title: "Results Analysis"
author: "Patrick Halbach, Johannes Nakayama"
date: "29 1 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r}

results <- read_csv(file.path("simulation", "results.csv"))

results$BatchName <- factor(x = results$BatchName, levels = c("Netsize", "Addfriends", "Unfriend"))
results$ConfigAgentCount <- as.factor(results$ConfigAgentCount)
results$ConfigUnfriendThresh <- as.factor(results$ConfigUnfriendThresh)
results$ConfigAddfriendMethod <- factor(x = results$ConfigAddfriendMethod, 
                                        levels = c("neighborsofneighbors", "hybrid", "random"), 
                                        labels = c("neighbors", "hybrid", "random"))

levels(results$ConfigAddfriendMethod)[1] <- "neighbors"

results %>% 
   mutate(Xlabel = case_when(BatchName == "Addfriends" ~ as.character(ConfigAddfriendMethod),
                           BatchName == "Unfriend" ~ as.character(ConfigUnfriendThresh),
                           BatchName == "Netsize" ~ as.character(ConfigAgentCount)),
         Xlevel = case_when(BatchName == "Addfriends" ~ as.numeric(ConfigAddfriendMethod),
                           BatchName == "Unfriend" ~ as.numeric(ConfigUnfriendThresh),
                           BatchName == "Netsize" ~ as.numeric(ConfigAgentCount))) -> results

```

```{r}

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(-c(BatchName, ConfigUnfriendThresh, ConfigAddfriendMethod, Xlabel, Xlevel)) %>% 
  group_by(ConfigAgentCount) %>% 
  summarise_all(mean) -> netsize_aggregates

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(-c(BatchName, ConfigUnfriendThresh, ConfigAgentCount, Xlabel, Xlevel)) %>% 
  group_by(ConfigAddfriendMethod) %>% 
  summarise_all(mean) -> addfriends_aggregates

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(-c(BatchName, ConfigAddfriendMethod, ConfigAgentCount, Xlabel, Xlevel)) %>% 
  group_by(ConfigUnfriendThresh) %>% 
  summarise_all(mean) -> unfriend_aggregates

```

```{r Combined Evaluation, fig.height=8, fig.width=8}

results %>% 
  # filter(BatchName == "Netsize") %>% 
  select(BatchName, Densities,ClosenessCentralityMean, CommunityCountNontrivial, OpinionSD, SupernodeBetweenness, Xlabel, Xlevel) %>% 
  gather("key", "value", Densities, ClosenessCentralityMean, CommunityCountNontrivial, OpinionSD, SupernodeBetweenness) %>% 
  mutate(key = factor(key, levels = c("Densities", 
                                      "ClosenessCentralityMean", 
                                      "CommunityCountNontrivial", 
                                      "OpinionSD", 
                                      "SupernodeBetweenness"))) %>% 
  group_by(BatchName, Xlabel,key) %>%
  arrange(Xlevel) %>% 
  ggplot(aes(x=reorder(Xlabel, Xlevel), y=value)) +
  facet_grid(key~BatchName, scales = "free", switch = "y", labeller = label_wrap_gen(width=10)) +
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill=Xlevel)) +
  theme(strip.text.y = element_text(angle = 180),
          axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0)),
          axis.title.y = element_blank(),
          panel.spacing = unit(1, "lines")) +
  scale_y_continuous(position = "right") +
  labs(x="Factor level", title="Factor influence overview") +
  theme(legend.position = "none") +
  scale_fill_viridis_c()
```


```{r combined eval first insight}

####    Degree Distributions    ####

results %>% 
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = Densities)) +
  facet_grid(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Densities") +
  scale_fill_viridis_c()

results %>% 
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = OutdegreeSD)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Outdegree SD") +
  scale_fill_viridis_c()

# results %>% 
#   mutate(OutdegreeMean = OutdegreeMean / as.numeric(ConfigAgentCount)) %>% 
#   ggplot(aes(x = reorder(Xlabel, Xlevel), y = OutdegreeMean)) +
#   facet_wrap(~BatchName, scales = "free_x") +
#   
#   geom_violin(alpha = 0.1, fill = "black", color = "NA") +
#   geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
#   theme(legend.position = "none") +
#   labs(x="Factor Configuration", title="Outdegree Mean relative to Network Size") +
#   scale_fill_viridis_c()

results %>% 
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = IndegreeSD)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Indegree SD") +
  scale_fill_viridis_c()

results %>% 
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = OutdegreeIndegreeRatioMean)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Outdegree Indegree Ratio") +
  scale_fill_viridis_c()

####    Centrality Measures ####

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = ClosenessCentralityMean)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Closeness Centrality") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = BetweennessCentralityMean)) +
  facet_wrap(~BatchName, scales = "free") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Betweenness Centrality") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = EigenCentralityMean)) +
  facet_wrap(~BatchName, scales = "free") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Eigenvector Centrality") +
  scale_fill_viridis_c()

####    Clustering and Community Structure    ####

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = ClustCoeff)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Cluster Coefficient") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = CommunityCountNontrivial)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Community Count") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = ConnectedComponents)) +
  facet_wrap(~BatchName, scales = "free") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Connected Components") +
  scale_fill_viridis_c()

####    Opinion Distribution    ####

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = OpinionSD)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Opinion SD") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = OpChangeDeltaMean)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Opinion Change Delta") +
  scale_fill_viridis_c()

results %>%
  filter(BatchName == "Addfriends") %>% 
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = PublOwnOpinionDiff)) +
  # facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Difference between perceived public and own opinion") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = CommunityOpMeanSDs)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Community Opinion Differences") +
  scale_fill_viridis_c()

####    Supernode Properties    ####

results %>%
  mutate(SupernodeOutdegree = SupernodeOutdegree / as.numeric(ConfigAgentCount)) %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = SupernodeOutdegree)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Supernode Outdegree relative to Net size") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = SupernodeCloseness)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Supernode Closeness") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = SupernodeBetweenness)) +
  facet_wrap(~BatchName, scales = "free") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Supernode Betweenness") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = SupernodeEigen)) +
  facet_wrap(~BatchName, scales = "free") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Supernode Eigenvector") +
  scale_fill_viridis_c()

results %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = SupernodeOpinion)) +
  facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.1, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Supernode Opinion") +
  scale_fill_viridis_c()

results %>%
  filter(BatchName == "Addfriends") %>%
  ggplot(aes(x = reorder(Xlabel, Xlevel), y = Supernode1st2ndOpdiff)) +
  # facet_wrap(~BatchName, scales = "free_x") +
  
  geom_violin(alpha = 0.3, fill = "black", color = "NA") +
  geom_boxplot(alpha = 0.5, aes(fill = Xlevel)) +
  theme(legend.position = "none") +
  labs(x="Factor Configuration", title="Opinion Difference between 1st and 2nd supernode") +
  scale_fill_viridis_c()


```


```{r netsize}

####    Degree Distribution    ####

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, Densities) %>% 
  ggplot(aes(x = ConfigAgentCount, y = Densities)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, OutdegreeSD) %>% 
  ggplot(aes(x = ConfigAgentCount, y = OutdegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, OutdegreeMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = OutdegreeMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, IndegreeSD) %>% 
  ggplot(aes(x = ConfigAgentCount, y = IndegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, IndegreeMax) %>% 
  ggplot(aes(x = ConfigAgentCount, y = IndegreeMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, OutdegreeIndegreeRatioMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = OutdegreeIndegreeRatioMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

####    Centrality Measures    ####

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, ClosenessCentralityMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = ClosenessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, BetweennessCentralityMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = BetweennessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, EigenCentralityMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = EigenCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

####    Clustering/Community Measures    ####

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, ClustCoeff) %>% 
  ggplot(aes(x = ConfigAgentCount, y = ClustCoeff)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  # select(ConfigAgentCount, CommunityCount, ConnectedComponents) %>% 
  mutate(CommunityCountClean = CommunityCount - ConnectedComponents + 1) %>% 
  ggplot(aes(x = ConfigAgentCount, y = CommunityCountClean)) +
  geom_jitter(alpha = 0.3, width = 0.2, height = 0.05) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(
    alpha = 0.6, 
    lwd = 0.8, 
    aes(fill = ConfigAgentCount, color = ConfigAgentCount)
  ) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(
    x = "Configuration", 
    y = "Number of Communities (Label Propagation)"
  )

####    Opinion Distribution Measures    ####

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, OpinionSD) %>% 
  ggplot(aes(x = ConfigAgentCount, y = OpinionSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, OpChangeDeltaMean) %>% 
  ggplot(aes(x = ConfigAgentCount, y = OpChangeDeltaMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, SupernodeOpinion) %>% 
  ggplot(aes(x = ConfigAgentCount, y = SupernodeOpinion)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, CommunityOpMeanSDs) %>% 
  ggplot(aes(x = ConfigAgentCount, y = CommunityOpMeanSDs)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

####    Supernode Measures    ####

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, SupernodeOutdegree) %>% 
  ggplot(aes(x = ConfigAgentCount, y = SupernodeOutdegree)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, SupernodeCloseness) %>% 
  ggplot(aes(x = ConfigAgentCount, y = SupernodeCloseness)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Netsize") %>% 
  select(ConfigAgentCount, SupernodeBetweenness) %>% 
  ggplot(aes(x = ConfigAgentCount, y = SupernodeBetweenness)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAgentCount)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  select(BatchName, ConfigAgentCount, ConfigUnfriendThresh, ConfigAddfriendMethod, SupernodeEigen) %>% 
  ggplot(aes(x = case_when(BatchName == "Addfriends" ~ as.character(ConfigAddfriendMethod),
                           BatchName == "Unfriend" ~ as.character(ConfigUnfriendThresh),
                           BatchName == "Netsize" ~ as.character(ConfigAgentCount)), y = SupernodeEigen)) +
  facet_wrap(~BatchName, scales = "free_x") +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = case_when(BatchName == "Addfriends" ~ as.character(ConfigAddfriendMethod),
                           BatchName == "Unfriend" ~ as.character(ConfigUnfriendThresh),
                           BatchName == "Netsize" ~ as.character(ConfigAgentCount)))) +
  theme_bw() +
  theme(legend.position = "none")

```

```{r addfriends}

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, Densities) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = Densities)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, OutdegreeSD) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OutdegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, OutdegreeMean) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OutdegreeMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, ConfigAddfriendMethod, OutdegreeMax) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OutdegreeMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")


results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, IndegreeSD) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = IndegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, IndegreeMax) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = IndegreeMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, OutdegreeIndegreeRatioMean) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OutdegreeIndegreeRatioMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, ClosenessCentralityMean) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = ClosenessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, ClosenessCentralityMax) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = ClosenessCentralityMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, BetweennessCentralityMean) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = BetweennessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, BetweennessCentralityMax) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = BetweennessCentralityMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, ClustCoeff) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = ClustCoeff)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  # select(ConfigAddfriendMethod, CommunityCount, ConnectedComponents) %>% 
  mutate(CommunityCountClean = CommunityCount - ConnectedComponents + 1) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = CommunityCountClean)) +
  geom_jitter(alpha = 0.3, width = 0.2, height = 0.05) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(
    alpha = 0.6, 
    lwd = 0.8, 
    aes(fill = ConfigAddfriendMethod, color = ConfigAddfriendMethod)
  ) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(
    x = "Configuration", 
    y = "Number of Communities (Label Propagation)"
  )

####    Opinion Distribution Measures    ####

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, OpinionSD) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OpinionSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, OpChangeDeltaMean) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = OpChangeDeltaMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, CommunityOpMeanSDs) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = CommunityOpMeanSDs)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

####    Supernode Measures    ####

results %>% 
  filter(BatchName == "Addfriends") %>% 
  select(ConfigAddfriendMethod, SupernodeCentrality) %>% 
  ggplot(aes(x = ConfigAddfriendMethod, y = SupernodeCentrality)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigAddfriendMethod)) +
  theme_bw() +
  theme(legend.position = "none")

```

```{r unfriend}

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, Densities) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = Densities)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, OutdegreeSD) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OutdegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, OutdegreeMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OutdegreeMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, ConfigUnfriendThresh, OutdegreeMax) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OutdegreeMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")


results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, IndegreeSD) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = IndegreeSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, IndegreeMax) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = IndegreeMax)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, OutdegreeIndegreeRatioMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OutdegreeIndegreeRatioMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, ClosenessCentralityMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = ClosenessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, BetweennessCentralityMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = BetweennessCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, EigenVectorCentralityMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = EigenVectorCentralityMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, ClustCoeff) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = ClustCoeff)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  # select(ConfigUnfriendThresh, CommunityCount, ConnectedComponents) %>% 
  mutate(CommunityCountClean = CommunityCount - ConnectedComponents + 1) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = CommunityCountClean)) +
  geom_jitter(alpha = 0.3, width = 0.2, height = 0.05) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(
    alpha = 0.6, 
    lwd = 0.8, 
    aes(fill = ConfigUnfriendThresh, color = ConfigUnfriendThresh)
  ) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(
    x = "Configuration", 
    y = "Number of Communities (Label Propagation)"
  )

####    Opinion Distribution Measures    ####

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, OpinionSD) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OpinionSD)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, OpChangeDeltaMean) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = OpChangeDeltaMean)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, CommunityOpMeanSDs) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = CommunityOpMeanSDs)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

####    Supernode Measures    ####

results %>% 
  filter(BatchName == "Unfriend") %>% 
  select(ConfigUnfriendThresh, SupernodeCentrality) %>% 
  ggplot(aes(x = ConfigUnfriendThresh, y = SupernodeCentrality)) +
  geom_jitter(alpha = 0.3, width = 0.2) +
  geom_violin(alpha = 0.1, fill = "black") +
  geom_boxplot(alpha = 0.5, aes(fill = ConfigUnfriendThresh)) +
  theme_bw() +
  theme(legend.position = "none")

```



